### ISSUE TITLE
Plugin library is not loading, certificate confirmation error.

### ISSUE THREAD

**Issue by Miskler** [DrMoriarty/nativelib#19]
![image](https://user-images.githubusercontent.com/69055489/235278846-81bc096c-44bc-40a8-84b5-a6282d558c90.png)

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KAMA\Documents\kHUTER-0.2.1.02\addons\NativeLib\nativelib", line 1148, in <module>
    storage_update()
  File "C:\Users\KAMA\Documents\kHUTER-0.2.1.02\addons\NativeLib\nativelib", line 313, in storage_update
    num = github_index_update()
  File "C:\Users\KAMA\Documents\kHUTER-0.2.1.02\addons\NativeLib\nativelib", line 209, in github_index_update
    download(url, 'master.tar.gz', path)
  File "C:\Users\KAMA\Documents\kHUTER-0.2.1.02\addons\NativeLib\nativelib", line 413, in download
    (filepath, headers) = urlretrieve(url, os.path.join(path, filename), reporthook=_progress)
  File "C:\Users\KAMA\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\KAMA\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\KAMA\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\KAMA\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\KAMA\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 557, in error
    result = self._call_chain(*args)
  File "C:\Users\KAMA\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\KAMA\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Users\KAMA\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Users\KAMA\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\KAMA\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\KAMA\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\KAMA\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'codeload.github.com'. (_ssl.c:997)>

 modules/gdscript/gdscript_functions.cpp:775 - NativeLib repository not found! Search at C:\Users\KAMA
/.nativelib/meta
 modules/gdscript/gdscript_functions.cpp:775 - Try to update repository info (button "REPO")
```

**Comment by Miskler** [comment]
```
 modules/gdscript/gdscript_functions.cpp:775 - NativeLib repository not found! Search at C:\Users\KAMA
/.nativelib/meta
 modules/gdscript/gdscript_functions.cpp:775 - Try to update repository info (button "REPO")

 modules/gdscript/gdscript_functions.cpp:789 - No platforms selected!
```
 
 This is what I get when I run the plugin. Installed the plugin yesterday (04/28/2023)

**Comment by Miskler** [comment]
![image](https://user-images.githubusercontent.com/69055489/235279801-16cbcd5a-228e-4c1e-87ad-b05beceb4a29.png)
I understood what the problem was. It is unclear how to solve(

Even with VPN I can't get access

**Comment by Miskler** [comment]
I rolled back the windows registry and I still have access in the browser, but Godot has the same error(
