### ISSUE TITLE
HTTP Error 403 downloading Ogury plugin

### ISSUE THREAD

**Issue by serogbp** [DrMoriarty/nativelib#9]
Hi! First of all, thank you for your hard work!
 
I'm trying to download the Ogury plugin from Godot GUI nativelib (not nativelib-cli) but I get the following error (HTTP Error 403 Forbidden):

```
 modules/gdscript/gdscript_functions.cpp:803 - Command python, exit code 1
Installing ogury@0.1.1
Traceback (most recent call last):
  File "C:\Users\me\Documents\Godot\godotGame\addons\NativeLib\nativelib", line 1416, in <module>
    install_package(p, v)
  File "C:\Users\me\Documents\Godot\godotGame\addons\NativeLib\nativelib", line 1186, in install_package
    download_package(package_name, version, package_meta)
  File "C:\Users\me\Documents\Godot\godotGame\addons\NativeLib\nativelib", line 674, in download_package
    path = download(f['url'], fname, home)
  File "C:\Users\me\Documents\Godot\godotGame\addons\NativeLib\nativelib", line 649, in download
    (filepath, headers) = urlretrieve(url, os.path.join(path, filename), reporthook=_progress)
  File "C:\Python38\lib\urllib\request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Python38\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python38\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Python38\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Python38\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Python38\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Python38\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

Could the problem be in this file? 
https://github.com/godot-asset/index/blob/master/meta/ogury/ogury_0.1.1_meta.json
- https://dl.bintray.com/mobilap/nativelib/ogury_0.1.1_all.tgz -> 403
- https://dl.bintray.com/mobilap/nativelib/ogury_0.1.1_android.tgz -> 403

My specs:
- Windows 10
- Godot 3.3 stable
- NativeLib 0.4.5
- Tried with python 3.9.5 and 3.8.5
- Enable Android for project

**Comment by DrMoriarty** [comment]
Hi @serogbp 
The bintray repository was closed In this month and I forget to reupload the plugin to github storage. Now I released new version to github, so it available to install.
Don't forget to update the local repository before installing it.

**Comment by serogbp** [comment]
Hey, sorry for not awsering sooner. I thought awsering will reopen the issue and I didn't wanted to bother you.

I could download Ogury without problems afer your fix :)
